apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          {{- if .valueFrom }}
          valueFrom:
            {{- if .valueFrom.configMapKeyRef }}
            configMapKeyRef:
              name: {{ include "demo-app.fullname" $ }}-config
              key: {{ .valueFrom.configMapKeyRef.key }}
            {{- else if .valueFrom.secretKeyRef }}
            secretKeyRef:
              name: {{ include "demo-app.fullname" $ }}-secrets
              key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          {{- else }}
          value: {{ .value | quote }}
          {{- end }}
        {{- end }}
